server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=clientes
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate     # Flyway se encarga del DDL
    open-in-view: false
  flyway:
    enabled: true
    schemas: clientes
    default-schema: clientes
  rabbitmq:
    host: localhost
    port: 5672

springdoc:
  api-docs:
    path: /api-docs
